dist: bionic

language: rust
rust:
  - 1.42.0

script:
  - cargo fmt --verbose --all
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace --tests --release
  - bash validator.sh
