dist: bionic

language: rust
rust:
  - 1.42.0

before_script:
  - rustup component add rustfmt --toolchain 1.42.0-x86_64-unknown-linux-gnu

script:
  - cargo fmt --verbose --all
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace --tests --release
  - bash validator.sh
